#Stores all nicknames for all vehicles currently supported

vehicleHash = {
  #NON TANKS
  "cnute" : "wWarden Heavy Truck",
  "heavytruck_w" : "wWarden Heavy Truck",
  "heavy_truck_w" :  "wWarden Heavy Truck",
  "cnute_cliffwrest" :  "wWarden Heavy Truck",
  "cliffwrest" :  "wWarden Heavy Truck",
  "rigger" : "cColonial Heavy Truck",
  "taurine" : "cColonial Heavy Truck",
  "taurine_rigger" : "cColonial Heavy Truck",
  "heavy_truck_c" : "cColonial Heavy Truck",
  "heavtruck_c" : "cColonial Heavy Truck",
  "flatbed" : "nFlatbed",
  "flatbed_truck" : "nFlatbed",
  "argo" : "cArgonaut",
  "jargo" : "cArgonaut",
  "luv" : "wDrummond",
  "drummond" : "wDrummond",
  #WARDEN PUSH GUNS
  "rampart" : "wBalfour Rampart",
  "balfour_rampart" : "wBalfour Rampart",
  "hv68" : "wBalfour Rampart",
  "ididthat" : "wBalfour Rampart",
  "fm" : "wFalconer Push 250",
  "push_250" : "wFalconer Push 250",
  "field_mortar" : "wFalconer Push 250",
  "push250" : "wFalconer Push 250",
  "fat_w" : "wWarden Collins FAT",
  "collins" : "wWarden Collins FAT",
  "push_40" : "wBalfour Wolfhound 40",
  "wolfhound" : "wBalfour Wolfhound 40",
  "balfour_wolfhound" : "wBalfour Wolfhound 40",
  "push40" : "wBalfour Wolfhound 40",
  "wasp" : "wWasp Nest Rocket Launcher",
  "wasp_nest" : "wWasp Nest Rocket Launcher",
  "field_launcher" : "wWasp Nest Rocket Launcher",
  "rycker" : "wWasp Nest Rocket Launcher",
  "fmg_w" : "wWarden FMG",
  "swallowtail" : "wWarden FMG",
  "coin" : "wWarden Push 20",
  "duncan_coin": "wWarden Push 20",
  "push_20_w" : "wWarden Push 20",
  "push_atr_w" : "wWarden Push 20",
  #COLLIE PUSH GUNS
  "smelter" : "cSmelter",
  "hv40" : "cSmelter",
  "fat_c" : "cBattering Ram FAT",
  "battering_ram" : "cBattering Ram FAT",
  "batter" : "cBattering Ram FAT",
  "fmg_c" : "cCollie FMG",
  "Sagittarii" : "cCollie FMG",
  "push_20_c" : "cCollie Push 20",
  "push_atr_c" : "cCollie Push 20",
  "cestus" : "cCollie Push 20",

  #WARDEN AC
  "obrien" : "wObrien V110 (AC)",
  "ac_w" : "wObrien V110 (AC)",
  "gravekeeper" : "wObrien V113 Gravekeeper",
  "bonewagon" : "wObrien V113 Gravekeeper",
  "tac" : "wObrien V121 Highlander (TAC)",
  "highlander" : "wObrien V121 Highlander (TAC)",
  "wild_jack" : "wObrien V130 Wild Jack (F-TAC)",
  "flame_tac" : "wObrien V130 Wild Jack (F-TAC)",
  "knave" : "wObrien V190 Knave (GAC)",
  "gac" : "wObrien V190 Knave (GAC)",
  "freeman" : "wObrien V101 Freeman (HAC)",
  "hac" : "wObrien V101 Freeman (HAC)",
  "rac" : "wObrien V200 Squire (RAC)",
  "squire" : "wObrien V200 Squire (RAC)",

  #COLLIE AC
  "ac_c" : "cT3 Xiphos (AC)",
  "t3" : "cT3 Xiphos (AC)",
  "xiphos" : "cT3 Xiphos (AC)",
  "t5" : "cT5 Percutio (ATAC)",
  "atac" : "cT5 Percutio (ATAC)",
  "Percutio" : "cT5 Percutio (ATAC)",
  "t8" : "cT8 Gemini (RPGAC)",
  "rpgac" : "cT8 Gemini (RPGAC)",
  "gemini" : "cT8 Gemini (RPGAC)",

  #WARDEN HALFTRACK AND VARIANTS
  "atht" : "wAT Half Track",
  "blinder" : "wAT Half Track",
  "niska" : "wHalf Track (Warden)",
  "halftrack" : "wHalf Track (Warden)",
  "ht_w" : "wHalf Track (Warden)",
  "ht_warden" : "wHalf Track (Warden)",
  "scar_twin" : "wScar Twin Half Track",
  "rocket_ht" : "wSkycaller Rocket Half Track",
  "rocket_half_track" : "wSkycaller Rocket Half Track",
  "skycaller" : "wSkycaller Rocket Half Track",

  #COLLIE HALFTRACK AND VARIANTS
  "mht" : "cMortar Half Track",
  "peltast" : "cMortar Half Track",
  "javelin" : "cHalf Track (Colonial)",
  "ht_c" : "cHalf Track (Colonial)",
  "ht_collie" : "cHalf Track (Colonial)",
  "hoplite" : "cHoplite Half Track",

  #WARDEN SCOUT TANK
  "king_spire" : "wKing Spire",
  "scout_tank" : "wKing Spire",
  "spire" : "wKing Spire",
  "gallant" : "wKing Gallant",
  "king_gallant" : "wKing Gallant",
  "30mm_scout" : "wKing Gallant",
  "jester" : "wKing Jester (Rocket)",
  "king_jester" : "wKing Jester (Rocket)",
  "rocket_scout" : "wKing Jester (Rocket)",
  "scout_rocket" : "wKing Jester (Rocket)",

  #WARDEN LIGHT TANKS
  "devitt" : "wDevitt",
  "devitt_mk_3" : "wDevitt",
  "devitt_mk3" : "wDevitt",
  "mk3" : "wDevitt",
  "devitt_ironhide" : "wDevitt Ironhide",
  "devitt_ironhide_mk_4" : "wDevitt Ironhide",
  "devitt_ironhide_mk4" : "wDevitt Ironhide",
  "ironhide" : "wDevitt Ironhide",
  "mk4" : "wDevitt Ironhide",
  "mlt" : "wDevitt Caine Mortar",
  "mortar_tank" : "wDevitt Caine Mortar",
  "caine" : "wDevitt Caine Mortar",
  "mmr" : "wDevitt Caine Mortar",
  "sharkey" : "wSharkey Devitt Birdeater (AA)",
  "birdeater" : "wSharkey Devitt Birdeater (AA)",
  "waavic" : "wSharkey Devitt Birdeater (AA)",
  "sharkey-devitt" : "wSharkey Devitt Birdeater (AA)",
  "bayshark" : "wSharkey Devitt Birdeater (AA)",
  "waatank" : "wSharkey Devitt Birdeater (AA)",
  #COLLIE LIGHT TANKS 
  "tankette" : "cT12 Tankette",
  "actaeon" : "cT12 Tankette",
  "vesta" : "cT14 Vesta (Flame)",
  "t14" : "cT14 Vesta (Flame)",
  "flametankette" : "cT14 Vesta (Flame)",
  "deioneus" : "cT13 Deioneus (Rocket)",
  "t13" : "cT13 Deioneus (Rocket)",
  "ixion" : "cT20 Ixion",
  "30mm_tankette" : "cT20 Ixion",
  "t20" : "cT20 Ixion",
  "hatchet" : "cHatchet",
  "hatch" : "cHatchet",
  "h5" : "cHatchet",
  "ltd" : "cPelekys (LTD)",
  "pelekys" : "cPelekys (LTD)",
  "h10" : "cPelekys (LTD)",
  "vulcan" : "cFlame Hatchet",
  "h19" : "cFlame Hatchet",
  "light_flame" : "cFlame Hatchet",
  "kranesca" : "cKranesca",
  "kranny" : "cKranesca",
  "h8" : "cKranesca",
  "ha1" : "cHA-1 Sagaris",
  "caavic" : "cHA-1 Sagaris (AA)",
  "caatank" : "cHA-1 Sagaris (AA)",
  "sagaris" : "cHA-1 Sagaris (AA)",
  "ha-1" : "cHA-1 Sagaris (AA)", 
  #WARDEN MEDIUM
  "svh" : "wSilverHand",
  "silverhand" : "wSilverHand",
  "chief" : "wChieftan",
  "chieftan" : "wChieftan",
  "std" : "wLordScar",
  "lordscar" : "wLordScar",
  "svh_std" : "wLordScar",
  "94_svh" : "wLordScar",
  "brig" : "wBrigand",
  "brigand" : "wBrigand",
  "isglaw" : "wBrigand",
  "hwm" : "wHighwayman",
  "highwayman" : "wHighwayman",
  "outlaw" : "wOutlaw",
  "larplaw" : "wOutlaw",
  "bonelaw" : "wThornfall",
  "thornfall" : "wThornfall",
  "htd" : "wWidow",
  "widow" : "wWidow",
  "noble_widow" : "wWidow",
  "flank" : "wWidow",
  "flame_widow" : "wFirebrand",
  "firebrand" : "wFirebrand",
  "heavy_flame_tank" : "wFirebrand",
  #COLLIE MEDIUM
  "mpt" : "cFalchion",
  "falchion" : "cFalchion",
  "spam" : "cFalchion",
  "spatha" : "cSpatha",
  "spartha" : "cSpatha",
  "85k" : "cSpatha",
  "talos" : "cTalos",
  "bard" : "cBardiche",
  "bardiche" : "cBardiche",
  "86k" : "cBardiche",
  "quad" : "cRanseur (Quadiche)",
  "quadiche" : "cRanseur (Quadiche)",
  "ranseur" :"cRanseur (Quadiche)",
  "86kc" : "cRanseur (Quadiche)",
  "rpg_bard" : "cRanseur (Quadiche)",
  "nemesis" : "cNemesis",
  "nem" : "cNemesis",
  "hotdog" : "cNemesis",
  "wheel_tank" : "cNemesis",
  "ist" : "cScorpion",
  "scorpion" : "cScorpion",
  "12.7_machine" : "cScorpion",
  "ballista" : "cBallista",
  "balls" : "cBallista",
  "ball" : "cBallista",
  #WARDEN SPECIAL
  "bt_w" : "wFlood (BT)",
  "flood" : "wFlood (BT)",
  "flood_bt" : "wFlood (BT)",
  "flame_bt" : "wJuggernaut (BT)",
  "juggernaut" : "wJuggernaut (BT)",
  "jugg" : "wJuggernaut (BT)",
  "spg_w" : "wStain (SPG)",
  "stain" : "wStain (SPG)",
  "flood_stain" : "wStain (SPG)",
  "cullen" : "wCullen Predator",
  "pred" : "wCullen Predator",
  "predator" : "wCullen Predator",
  "cullen_predator" : "wCullen Predator",
  "sht_w" : "wCullen Predator",
  "sht_warden" : "wCullen Predator",
  #COLLIE SPEICAL
  "bt_c" : "cLance (BT)",
  "lance" : "cLance (BT)",
  "collie_bt" : "cLance (BT)",
  "btd" : "cHasta (BTD)",
  "hasta" : "cHasta (BTD)",
  "lance25" : "cHasta (BTD)",
  "spg_c" : "cSarissa (SPG)",
  "sarissa" : "cSarissa (SPG)",
  "ares" : "cAres",
  "075b" : "cAres",
  "sht_c" : "cAres",
  "sht_collie" : "cAres",
  #MISC
  "push120" : "c120mm Artillery",
  "fa" : "c120mm Artillery",
  "collie_artillery" : "c120mm Artillery",
  "field_arty" : "c120mm Artillery",
  "push_120" : "c120mm Artillery",
  "push_arty" : "c120mm Artillery",
  "koronides" : "c120mm Artillery",
  "stockade" : "wStockade",
  "balfour" : "wStockade",
  "styg" : "cStygian",
  "stygian" : "cStygian",
  "retiarius" : "cCollie Rocket Truck",
  "skirmisher" : "cCollie Rocket Truck",
  "katyusha" : "cCollie Rocket Truck",
  "rocket_truck" : "cCollie Rocket Truck",
  "r-17" : "cCollie Rocket Truck",
  "alekto" : "cAlekto 250mm",
  "35-250" : "cAlekto 250mm",
  #SHIPS
  "nakki" : "wSubmarine",
  "sub_w" : "wSubmarine",
  "submarine_w" : "wSubmarine",
  "trident" : "cSubmarine",
  "sub_c" : "cSubmarine",
  "submarine_c" : "cSubmarine",
  "frigate" : "wBlacksteele Frigate",
  "blacksteele" : "wBlacksteele Frigate",
  "destroyer" : "cConqueror Destroyer",
  "conqueror" : "cConqueror Destroyer",
  "callahan" : "wCallahan Battleship",
  "bs_w" : "wCallahan Battleship",
  "battleship_w" : "wCallahan Battleship",
  "battleship_warden" : "wCallahan Battleship",
  "titan" : "cTitan Battleship",
  "battleship_c" : "cTitan Battleship",
  "bs_c" : "cTitan Battleship",
  "battleship_colonial" : "cTitan Battleship",
  "gb_c" : "cCharon Gunboat",
  "charon" : "cCharon Gunboat",
  "gb_w" : "wRonan Gunboat",
  "ronan" : "wRonan Gunboat",

  #Non Armored
  "crane" : "nCrane",
  "cv" : "nConstruction Vehicle", 
  "construction_vehicle" : "nConstruction Vehicle",
  "small_gauge" : "nSmall Gauge Train", 
  "mineseeker" : "nSmall Gauge Train",
  "train" : "nBMS Blackbolt",
  "blackbolt" : "nBMS Blackbolt",
  "armored_train_w" : "wObrien Warsmith (Combat Car)",
  "warsmith" : "wObrien Warsmith (Combat Car)",
  "armored_train_c" : "cAegis Steelbreaker (Combat Car)",
  "aegis_steelbreaker" : "cAegis Steelbreaker (Combat Car)",
  "steelbreaker" : "cAegis Steelbreaker (Combat Car)",
  #SILLY
  "infantry" : "nInfantry",
  "qrf" : "nInfantry",
  "knower" : "nInfantry",
  "proto" : "nProto",
  "prototype" : "nProto",
  "watchtower" : "nWatchtower",
  "wt" : "nWatchtower",
  "bmat" : "nBmat",

  #PLANES
  "collie_scoutplane" : "cScoutPlane (Colonial)",
  "scoutplane_c" : "cScoutPlane (Colonial)",
  "warden_scoutplane" : "wScoutPlane (Warden)",
  "scoutplane_w" : "wScoutPlane (Warden)",

  #FIGHTERS
  "harbringer" : "wLuminary Mk. II Harbringer",
  "wFighter" : "wLuminary Mk. II Harbringer",
  
  "toxot" : "cToxot-902 Blinder Silver",
  "blindsilver" : "cToxot-902 Blinder Silver",
  "Fighter" : "cToxot-902 Blinder Silver",

  "seafighter_w" : "wTulka I1.9 White Raven",
  "f22" : "wTulka I1.9 White Raven",
  "ufo" : "wTulka I1.9 White Raven",
  "whiteraven" : "wTulka I1.9 White Raven",

  #DB
  "myrmidon" : "cMergo-4 Myrmidon",
  "skyhitler" : "cMergo-4 Myrmidon",
  "hitler" : "cMergo-4 Myrmidon",
  "mergo" : "cMergo-4 Myrmidon",
  "db_c" : "cMergo-4 Myrmidon",

  #TB
  "tb_w" : "wM925 Austringer Man-O-War",
  "austringer" : "wM925 Austringer Man-O-War",
  "manowar" : "wM925 Austringer Man-O-War",
  "torpedo_w" : "wM925 Austringer Man-O-War",

  #BOMBEES

  "bomber_w" : "wTulka P4 Welkinrive (Bomber)",
  "blueskies" : "wTulka P4 Welkinrive (Bomber)",
  "welkinrive" : "wTulka P4 Welkinrive (Bomber)",

  "tzykalia" : "cV-1 Tzykalia (Bomber)",
  "bomber_c" : "cV-1 Tzykalia (Bomber)",
  "v-1" : "cV-1 Tzykalia (Bomber)",

  #PARAS

  "rinnspeir" : "wRinnspeir Mk. 1 Zealot",
  "zealot" : "wRinnspeir Mk. 1 Zealot",
  "para_w" : "wRinnspeir Mk. 1 Zealot",

  "pegasus" : "cV-5b Pegasus",
  "v-5b":  "cV-5b Pegasus",
  "para_c" : "cV-5b Pegasus",
 


}